from enum import Enum

class UserRole(str, Enum):
    ADMIN = "ADMIN"
    COORDINATOR = "COORDINATOR"

class CertificateStatus(str, Enum):
    VALID = "VALID"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"

class JobStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    PARTIALLY_FAILED = "PARTIALLY_FAILED"

class ItemStatus(str, Enum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"

class EmailStatus(str, Enum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"

class AuditAction(str, Enum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    CREATE_COORDINATOR = "CREATE_COORDINATOR"
    DISABLE_COORDINATOR = "DISABLE_COORDINATOR"
    ENABLE_COORDINATOR = "ENABLE_COORDINATOR"
    CREATE_TEMPLATE = "CREATE_TEMPLATE"
    UPDATE_TEMPLATE = "UPDATE_TEMPLATE"
    DELETE_TEMPLATE = "DELETE_TEMPLATE"
    CREATE_EVENT = "CREATE_EVENT"
    UPLOAD_EXCEL = "UPLOAD_EXCEL"
    START_GENERATION = "START_GENERATION"
    GENERATE_CERTIFICATE = "GENERATE_CERTIFICATE"
    SEND_EMAIL = "SEND_EMAIL"
    RETRY_EMAIL = "RETRY_EMAIL"
    REVOKE_CERTIFICATE = "REVOKE_CERTIFICATE"
    UPDATE_SMTP = "UPDATE_SMTP"
    FAILED_AUTH = "FAILED_AUTH"

class TemplatePageSize(str, Enum):
    A4 = "A4"
    LETTER = "LETTER"

class TemplateOrientation(str, Enum):
    LANDSCAPE = "LANDSCAPE"
    PORTRAIT = "PORTRAIT"

class ElementType(str, Enum):
    TEXT = "TEXT"
    QR = "QR"
    LINE = "LINE"
    RECTANGLE = "RECTANGLE"
    IMAGE_PLACEHOLDER = "IMAGE_PLACEHOLDER"
